version: '3.8'

services:
  php-apache:
    container_name: wend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '5580:80'
    volumes:
      - .:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    networks:
      - wend-net

  mysql:
    platform: linux/amd64
    image: mysql:8.0.26
    container_name: wend-database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wend_db
      # MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - wend-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - wend-net

networks:
  wend-net:
    driver: "bridge"

volumes:
  mysqldata:
    driver: local